import assert from 'node:assert/strict';
import { cp, mkdtemp, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { describe, it } from 'node:test';
import { dependencyPaths, loadDependencyGraph, lockfileManager, nodesByName } from '../../src/evidence/lockfile.ts';
import { npmAlias } from '../../src/evidence/lockfiles/index.ts';
import {
  parseResolutionKey,
  parseYarnBerry,
  parseYarnClassic,
  parseYarnClassicEntries,
  parseYarnLockfile,
  patchedLocator,
  removeYarnClassicRequests,
  yarnFlavor,
} from '../../src/evidence/lockfiles/yarn.ts';
import { LOCKFILES, rootEdges, summarize, text, workspacePackages, workspacesNpmGraph } from './yarn-pnpm-helpers.ts';

describe('yarn 1 lockfile: workspaces, scopes, an alias, optional and dev dependencies', async () => {
  const { root, workspaces } = await workspacePackages();
  const graph = parseYarnClassic(await text('workspaces', 'yarn.lock'), { rootPackage: root, workspaces });

  it('matches the npm graph except the peer edge (yarn 1 records no peer dependencies)', async () => {
    const npm = summarize(await workspacesNpmGraph());
    // yarn.lock has no peer edge to react
    npm['react@18.2.0'] = { ...(npm['react@18.2.0'] as (typeof npm)[string]), parents: [''], paths: ['react@18.2.0'] };
    npm['loose-envify@1.4.0'] = { ...(npm['loose-envify@1.4.0'] as (typeof npm)[string]), paths: ['react@18.2.0 > loose-envify@1.4.0'] };
    npm['js-tokens@4.0.0'] = { ...(npm['js-tokens@4.0.0'] as (typeof npm)[string]), paths: ['react@18.2.0 > loose-envify@1.4.0 > js-tokens@4.0.0'] };
    assert.deepEqual(summarize(graph), npm);
  });

  it('treats workspace folders as importers (first-party, not packages)', () => {
    assert.deepEqual(graph.workspaceKeys, ['packages/a', 'packages/b']);
    assert.deepEqual(graph.nodes.get('is-odd@3.0.1')?.parents, ['packages/a']);
    assert.deepEqual(dependencyPaths(graph, 'ms@2.1.2'), [['packages/b', 'debug@4.3.4', 'ms@2.1.2']]);
    assert.equal(graph.nodes.get('has-flag@4.0.0')?.dev, true, 'a devDependency of packages/a and of the dev-only supports-color');
    assert.equal(graph.nodes.get('is-number@7.0.0')?.optional, true);
    assert.equal(graph.nodes.get('is-number@6.0.0')?.optional, false);
    assert.deepEqual(nodesByName(graph, 'ms').map((n) => n.version).sort(), ['2.0.0', '2.1.2', '2.1.3']);
  });

  it('maps an npm alias to the real package and keeps the alias as the key', () => {
    const alias = graph.nodes.get('my-lodash@npm:lodash@4.17.21');
    assert.equal(alias?.name, 'lodash');
    assert.equal(alias?.alias, 'my-lodash');
    assert.equal(graph.root.edges['my-lodash'], 'my-lodash@npm:lodash@4.17.21');
    assert.deepEqual(graph.byName.get('lodash'), ['my-lodash@npm:lodash@4.17.21']);
  });

  it('loadDependencyGraph expands the workspace globs and reads their package.json', async () => {
    const tmp = await mkdtemp(path.join(os.tmpdir(), 'pp-yarn1-'));
    try {
      await cp(path.join(LOCKFILES, 'workspaces'), tmp, { recursive: true, filter: (src) => !/berry|pnpm/.test(path.basename(src)) && !src.endsWith('package-lock.json') });
      const loaded = await loadDependencyGraph(tmp, path.join(tmp, 'yarn.lock'));
      assert.deepEqual(summarize(loaded), summarize(graph));
      assert.equal(lockfileManager(path.join(tmp, 'yarn.lock')), 'yarn');
    } finally {
      await rm(tmp, { recursive: true, force: true });
    }
  });
});

describe('yarn 1 text format', () => {
  const LOCK = [
    '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.',
    '# yarn lockfile v1',
    '',
    '',
    '"@babel/code-frame@^7.0.0", "@babel/code-frame@^7.10.4":',
    '  version "7.12.13"',
    '  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.12.13.tgz#dcfc826beef65e75c50e21d3837d7d95798dd658"',
    '  integrity sha512-HV1Cm0Q3ZrpCR93tkWOYiuYIgLxZXZFVG2VgK+MBWjUqZTundupbfx2aXarXuw5Ko5aMcjtJgbSs4vUGBS5v6g==',
    '  dependencies:',
    '    "@babel/highlight" "^7.12.13"',
    '',
    '"@babel/highlight@^7.12.13":',
    '  version "7.13.10"',
    '  resolved "https://registry.yarnpkg.com/@babel/highlight/-/highlight-7.13.10.tgz#a8b2a66148f5b27d666b15d81774347a731d52d1"',
    '  dependencies:',
    '    js-tokens "^4.0.0"',
    '  optionalDependencies:',
    '    fsevents "~2.3.1"',
    '',
    '"js-tokens@^3.0.0 || ^4.0.0", js-tokens@^4.0.0:',
    '  version "4.0.0"',
    '',
    'fsevents@~2.3.1:',
    '  version "2.3.2"',
    '',
  ].join('\r\n');

  it('parses quoted, comma-separated and spaced requests, CRLF, nested dependencies', () => {
    const entries = parseYarnClassicEntries(LOCK);
    assert.deepEqual(entries.map((e) => e.patterns), [
      ['@babel/code-frame@^7.0.0', '@babel/code-frame@^7.10.4'],
      ['@babel/highlight@^7.12.13'],
      ['js-tokens@^3.0.0 || ^4.0.0', 'js-tokens@^4.0.0'],
      ['fsevents@~2.3.1'],
    ]);
    assert.deepEqual(entries[1]?.data.dependencies, { 'js-tokens': '^4.0.0' });
    assert.deepEqual(entries[1]?.data.optionalDependencies, { fsevents: '~2.3.1' });
    const graph = parseYarnClassic(LOCK, { rootPackage: { name: 'x', dependencies: { '@babel/code-frame': '^7.10.4' } } });
    assert.equal(graph.root.edges['@babel/code-frame'], '@babel/code-frame@7.12.13');
    assert.equal(graph.nodes.get('@babel/highlight@7.13.10')?.edges['js-tokens'], 'js-tokens@4.0.0');
    assert.equal(graph.nodes.get('fsevents@2.3.2')?.optional, true, 'reached only through optionalDependencies');
    assert.equal(graph.nodes.get('js-tokens@4.0.0')?.optional, false);
  });

  it('falls back to the entry whose version satisfies a request the lockfile does not list', () => {
    const graph = parseYarnClassic(LOCK, { rootPackage: { name: 'x', dependencies: { 'js-tokens': '4.x' } } });
    assert.equal(graph.root.edges['js-tokens'], 'js-tokens@4.0.0');
  });

  it('refuses merge-conflict markers with the command that regenerates the lockfile', () => {
    assert.throws(() => parseYarnClassicEntries('<<<<<<< HEAD\nlodash@^4:\n  version "4.17.20"\n'), /merge conflict markers \(line 1\).*yarn install/);
  });

  it('removes requests so yarn re-resolves them, keeping the other requests of an entry', async () => {
    const lock = await text('after', 'yarn1-bump-minimist.lock');
    const { text: next, removed } = removeYarnClassicRequests(lock, (request, version) => request === 'minimist@^1.2.5' && version === '1.2.5');
    assert.deepEqual(removed, ['minimist@^1.2.5']);
    assert.doesNotMatch(next, /minimist@\^1\.2\.5/);
    assert.match(next, /\nminimist@1\.2\.6:\n {2}version "1\.2\.6"/);
    assert.equal(parseYarnClassicEntries(next).length, parseYarnClassicEntries(lock).length - 1);
    const shared = removeYarnClassicRequests(LOCK, (request) => request === 'js-tokens@^4.0.0');
    assert.match(shared.text, /\r\n"js-tokens@\^3\.0\.0 \|\| \^4\.0\.0":\r\n {2}version "4\.0\.0"/, 'the entry stays for its other request, CRLF kept');
  });
});

describe('yarn 2+ lockfile: workspaces, aliases, peers', async () => {
  const { root, workspaces } = await workspacePackages();
  const graph = parseYarnBerry(await text('workspaces', 'berry', 'yarn.lock'), { rootPackage: root, workspaces });

  it('matches the npm graph exactly, peer edge included', async () => {
    assert.deepEqual(summarize(graph), summarize(await workspacesNpmGraph()));
    assert.deepEqual(rootEdges(graph), rootEdges(await workspacesNpmGraph()));
  });

  it('resolves a peer dependency through the dependent that provides it', () => {
    const sync = graph.nodes.get('use-sync-external-store@npm:1.2.0');
    assert.equal(sync?.edges.react, 'react@npm:18.2.0');
    assert.equal(sync?.requires.react, '^16.8.0 || ^17.0.0 || ^18.0.0');
    assert.ok(graph.nodes.get('react@npm:18.2.0')?.parents.includes('use-sync-external-store@npm:1.2.0'));
  });

  it('maps workspace entries to folders and an alias to its package', () => {
    assert.deepEqual(graph.workspaceKeys, ['packages/a', 'packages/b']);
    assert.equal(graph.root.edges['my-lodash'], 'lodash@npm:4.17.21');
    assert.equal(graph.nodes.get('lodash@npm:4.17.21')?.alias, 'my-lodash');
    assert.equal(graph.nodes.has('@patchpilot-fixture/a@workspace:packages/a'), false);
  });

  it('without the workspace package.json files, the lockfile sections are used (dev unknown)', async () => {
    const bare = parseYarnBerry(await text('workspaces', 'berry', 'yarn.lock'));
    assert.equal(bare.root.name, 'cx-root');
    assert.equal(bare.nodes.get('is-number@npm:7.0.0')?.optional, true, 'dependenciesMeta optional');
    assert.equal(bare.nodes.get('ms@npm:2.1.3')?.dev, false, 'yarn.lock does not say it is a devDependency');
  });
});

describe('yarn 2+ details', () => {
  it('folds a builtin patch: locator into the package it patches', () => {
    const lock = [
      '__metadata:',
      '  version: 8',
      '  cacheKey: 10c0',
      '',
      '"resolve@npm:^1.20.0":',
      '  version: 1.22.8',
      '  resolution: "resolve@npm:1.22.8"',
      '  checksum: 10c0/abc',
      '  languageName: node',
      '  linkType: hard',
      '',
      '"resolve@patch:resolve@npm%3A^1.20.0#optional!builtin<compat/resolve>":',
      '  version: 1.22.8',
      '  resolution: "resolve@patch:resolve@npm%3A1.22.8#optional!builtin<compat/resolve>::version=1.22.8&hash=c3c19d"',
      '  checksum: 10c0/def',
      '  languageName: node',
      '  linkType: hard',
      '',
      '"app@workspace:.":',
      '  version: 0.0.0-use.local',
      '  resolution: "app@workspace:."',
      '  dependencies:',
      '    resolve: "patch:resolve@npm%3A^1.20.0#optional!builtin<compat/resolve>"',
      '  languageName: unknown',
      '  linkType: soft',
      '',
    ].join('\n');
    assert.equal(patchedLocator('resolve@patch:resolve@npm%3A1.22.8#optional!builtin<compat/resolve>::version=1.22.8&hash=c3c19d'), 'resolve@npm:1.22.8');
    const graph = parseYarnBerry(lock, { rootPackage: { name: 'app', dependencies: { resolve: '^1.20.0' } } });
    assert.deepEqual([...graph.nodes.keys()], ['resolve@npm:1.22.8']);
    assert.equal(graph.root.edges.resolve, 'resolve@npm:1.22.8');
    assert.equal(graph.lockfileVersion, 8);
  });

  it('tells yarn 1 from yarn 2+ and reads resolution keys', async () => {
    assert.equal(yarnFlavor(await text('workspaces', 'yarn.lock')), 'classic');
    assert.equal(yarnFlavor(await text('workspaces', 'berry', 'yarn.lock')), 'berry');
    assert.equal(parseYarnLockfile(await text('workspaces', 'berry', 'yarn.lock')).packageManager, 'yarn-berry');
    assert.deepEqual(parseResolutionKey('query-string/decode-uri-component'), { from: 'query-string', name: 'decode-uri-component' });
    assert.deepEqual(parseResolutionKey('query-string@^6/decode-uri-component'), { from: 'query-string', name: 'decode-uri-component' });
    assert.deepEqual(parseResolutionKey('@s/parent/@s/child'), { from: '@s/parent', name: '@s/child' });
    assert.deepEqual(parseResolutionKey('**/lodash'), { from: null, name: 'lodash' });
    assert.deepEqual(parseResolutionKey('lodash@^4'), { from: null, name: 'lodash' });
    assert.equal(npmAlias('npm:^0.2.0'), null, 'yarn 2+ writes every registry range with the npm protocol');
    assert.deepEqual(npmAlias('npm:lodash@4.17.21'), { name: 'lodash', range: '4.17.21' });
  });

  it('explains invalid YAML', () => {
    assert.throws(() => parseYarnBerry('__metadata:\n  version: 8\n"a@npm:1":\n  version: [\n'), /not valid YAML.*yarn install/s);
  });
});
